---
# tasks file for kvm_lab
# tasks files on main.yml as include arguments
#- include: preinstall.yml
- include: install.yml
- include: netinstall.yml
- include: templateinstall.yml
- include: scripts.yml
