---
# Create new Networks / delete unused Networks
#- name: create bridged WAN network
- virt_net:
    command: define
    name: wan01
    xml: '{{ lookup("template", "if_wan01.xml.j2") }}'
    state: active
    autostart: yes
